---
- name: Create 3 Tier App
  hosts: apic
  connection: local
  gather_facts: no

  vars:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password }}'
      use_proxy: no
      validate_certs: no
    tenant: "CiscoLive"
    vrf: VRF1
    ap: APP1
    vmmdomain: ACI-vDS

    bds:
      - bd: "BD-Web"
        gateway: "192.168.1.254"
        mask: "24"
        scope: "public"
      - bd: "BD-App"
        gateway: "192.168.2.254"
        mask: "24"
        scope: "private"
      - bd: "BD-DB"
        gateway: "192.168.3.254"
        mask: "24"
        scope: "private"
    epgs:
      - epg: "Web"
        bd: "BD-Web"
      - epg: "App"
        bd: "BD-App"
      - epg: "DB"
        bd: "BD-DB"

  tasks:
    - name: TASK 01 - Create Tenant
      aci_tenant:
        <<: *aci_login
        tenant: "{{ tenant }}"

    - name: TASK 02 - Create VRF
      aci_vrf:
        <<: *aci_login
        tenant: "{{ tenant }}"
        vrf: "{{ vrf }}"

    - name: TASK 03 - Create BD
      aci_bd:
        <<: *aci_login
        tenant: "{{ tenant }}"
        bd: "{{ item.bd }}"
        vrf: "{{ vrf }}"
        enable_routing: yes
        arp_flooding: yes
        l2_unknown_unicast: flood
      with_items: "{{ bds }}"

    - name: TASK 04 - Create BD subnets
      aci_bd_subnet:
        <<: *aci_login
        tenant: "{{ tenant }}"
        bd: "{{ item.bd }}"
        gateway: "{{ item.gateway }}"
        mask: "{{ item.mask }}"
        scope: "{{ item.scope }}"
      with_items: "{{ bds }}"

    - name: TASK 05 - Create AP
      aci_ap:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"

    - name: TASK 06 - Create EPG
      aci_epg:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        bd: "{{ item.bd }}"
      with_items: "{{ epgs }}"

    - name: TASK 07 - Associate EPG to domain
      aci_epg_to_domain:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        domain: "{{ vmmdomain }}"
        domain_type: vmm
        vm_provider: vmware
        encap_mode: "auto"
      with_items: "{{ epgs }}"
